### PR TITLE
Added files which were moved and forgotten at their new location

### PR DESCRIPTION
**Pull request by pastika**

### CODE REVIEW

**Comment by pastika** [comment]
No, it is for producing isotrack variables

**Comment by hatakeyamak** [comment]
StopTupleMaker/SkimsAUX/workdir/prod/treeMaker_stopRA2.py
ixEE2017Params = {'userawPt': True, 'PtThreshold':50.0, 'MinEtaThreshold':2.65, 'MaxEtaThreshold': 3.139} ,
->
fixEE2017Params = {'userawPt': True, 'ptThreshold':50.0, 'minEtaThreshold':2.65, 'maxEtaThreshold': 3.139} ,
is probably necessary. Thank you!

**Comment by scarletnorberg** [comment]
I believe that those lines are needed for the Met fix in 2017

**Comment by pastika** [comment]
Fix added

**Comment by scarletnorberg** [comment]
Oh I see it now. I have trouble with capital not capital letters. Thanks

**Pull request merged**
